In [1]:
import pandas as pd
import mysql.connector 

connection = mysql.connector.connect(
    host = "Localhost",
    user = "root",
    password = "12345",
    database="market_analysis"
)
cursor =  connection.cursor()
cursor

# Overall Campaign Acceptance Rate

In [4]:
query="""SELECT 
    ROUND((SUM(AcceptedCmp1)+SUM(AcceptedCmp2)+SUM(AcceptedCmp3)+SUM(AcceptedCmp4)+SUM(AcceptedCmp5)+SUM(Response))*100.0/(COUNT(*)*6), 2) AS OVERALL_response_rate
    FROM marketing_campaigns_data"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_16204\2092831590.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

   OVERALL_response_rate
0                   7.69

# Average spend

In [6]:
query="SELECT ROUND(AVG(Total_Spend),2) AS AVG_customer_spend FROM derived_table"
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_16204\3977203078.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

   AVG_customer_spend
0              640.19

# Average spend per segment

In [7]:
query="""SELECT
    ROUND(AVG(MntWines),2) AS Avg_on_wines,
    ROUND(AVG(MntFruits),2) AS Avg_on_fruits,
    ROUND(AVG(MntMeatProducts),2) AS Avg_on_meat,
    ROUND(AVG(MntFishProducts),2) AS Avg_on_fish,
    ROUND(AVG(MntSweetProducts),2) AS Avg_on_sweets,
    ROUND(AVG(MntGoldProds),2) AS Avg_on_gold
     
    FROM marketing_campaigns_data"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_16204\3020037079.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

,Avg_on_wines,Avg_on_fruits,Avg_on_meat,Avg_on_fish,Avg_on_sweets,Avg_on_gold
0,246.98,16.15,268.29,51.1,22.42,35.39

# Average store, web and catalog purchases

In [8]:
query="""SELECT
    ROUND(AVG(NumStorePurchases),2) AS Avg_store_purchases,
    ROUND(AVG(NumWebPurchases),2) AS Avg_web_purchases,
    ROUND(AVG(NumCatalogPurchases),2) AS Avg_catalog_purchases
     
    FROM marketing_campaigns_data"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_16204\3384188554.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

   Avg_store_purchases  Avg_web_purchases  Avg_catalog_purchases
0                 4.71               4.25                   2.11

# Average website visits

In [9]:
query="""SELECT
    ROUND(AVG(NumWebVisitsMonth),2) AS Avg_web_visit
    FROM marketing_campaigns_data"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_16204\1534687611.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

   Avg_web_visit
0           5.17

# KPI by Education

In [13]:
query="""SELECT m.Education, COUNT(*) AS Customers,
    ROUND(AVG(d.Total_Spend),2) AS Avg_Spend,
    ROUND(AVG(m.NumWebVisitsMonth),2) AS Avg_Web_Visits,
    ROUND((SUM(m.AcceptedCmp1)+SUM(m.AcceptedCmp2)+SUM(m.AcceptedCmp3)+SUM(m.AcceptedCmp4)+SUM(m.AcceptedCmp5)+SUM(m.Response))*100.0/(COUNT(*)*6), 2) AS Overall_response_rate
    
    FROM marketing_campaigns_data m
    JOIN derived_table d
    ON m.ID=d.ID
    
    GROUP BY Education
    ORDER BY Avg_Spend DESC"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_16204\445894664.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

    Education  Customers  Avg_Spend  Avg_Web_Visits  Overall_response_rate
0  Graduation      22735     747.23            4.90                   9.17
1      Master      10527     648.25            5.19                   6.97
2         PhD      12579     575.65            5.36                   7.14
3    2n Cycle       5964     511.04            5.40                   6.07
4       Basic       4181     416.24            5.69                   5.39

# KPI by Age band

In [17]:
query="""SELECT 
    CASE
        WHEN Age BETWEEN 30 AND 44 THEN 'Young Adults'
        WHEN Age BETWEEN 45 AND 59 THEN 'Middle Aged'
        ELSE 'Senior Adults'
    END AS Age_band,
    COUNT(*) AS Customers,
    ROUND(AVG(d.Total_Spend),2) AS Avg_Spend,
    ROUND(AVG(m.NumWebVisitsMonth),2) AS Avg_Web_Visits,
    ROUND((SUM(m.AcceptedCmp1)+SUM(m.AcceptedCmp2)+SUM(m.AcceptedCmp3)+SUM(m.AcceptedCmp4)+SUM(m.AcceptedCmp5)+SUM(m.Response))*100.0/(COUNT(*)*6), 2) AS Overall_response_rate
    
    FROM marketing_campaigns_data m
    JOIN derived_table d ON m.ID=d.ID
     
    GROUP BY Age_band
    ORDER BY Avg_Spend DESC"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_16204\3008615507.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

        Age_band  Customers  Avg_Spend  Avg_Web_Visits  Overall_response_rate
0  Senior Adults      18338     788.60            4.87                   9.09
1    Middle Aged      24929     602.63            5.26                   7.36
2   Young Adults      12719     499.84            5.43                   6.30

# KPI by marital status

In [15]:
query="""SELECT m.Marital_Status, COUNT(*) AS Customers,
    ROUND(AVG(d.Total_Spend),2) AS Avg_Spend,
    ROUND(AVG(m.NumWebVisitsMonth),2) AS Avg_Web_Visits,
    ROUND((SUM(m.AcceptedCmp1)+SUM(m.AcceptedCmp2)+SUM(m.AcceptedCmp3)+SUM(m.AcceptedCmp4)+SUM(m.AcceptedCmp5)+SUM(m.Response))*100.0/(COUNT(*)*6), 2) AS Overall_response_rate
    
    FROM marketing_campaigns_data m
    JOIN derived_table d
    ON m.ID=d.ID
    
    GROUP BY m.Marital_Status
    ORDER BY Avg_Spend DESC"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_16204\746423745.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

  Marital_Status  Customers  Avg_Spend  Avg_Web_Visits  Overall_response_rate
0       Divorced       6459     753.91            4.82                   8.86
1          Widow       3539     745.03            4.63                   9.81
2          Alone        910     700.36            5.11                  11.03
3         Single      12235     688.00            5.19                   8.20
4           YOLO        730     665.59            5.02                  10.59
5         Absurd        733     655.35            5.30                   8.64
6       Together      17698     644.57            5.18                   7.21
7        Married      13682     504.80            5.46                   6.31

# KPI by country

In [16]:
query="""SELECT m.Country, COUNT(*) AS Customers,
    ROUND(AVG(d.Total_Spend),2) AS Avg_Spend,
    ROUND(AVG(m.NumWebVisitsMonth),2) AS Avg_Web_Visits,
    ROUND((SUM(m.AcceptedCmp1)+SUM(m.AcceptedCmp2)+SUM(m.AcceptedCmp3)+SUM(m.AcceptedCmp4)+SUM(m.AcceptedCmp5)+SUM(m.Response))*100.0/(COUNT(*)*6), 2) AS Overall_response_rate
    
    FROM marketing_campaigns_data m
    JOIN derived_table d
    ON m.ID=d.ID
    
    GROUP BY m.Country
    ORDER BY Avg_Spend DESC"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_16204\1751517591.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

        Country  Customers  Avg_Spend  Avg_Web_Visits  Overall_response_rate
0     Australia       5673     826.93            4.89                   9.68
1         India       4813     723.80            4.97                   8.79
2       Germany       4432     707.24            4.94                   8.36
3           USA       4330     663.67            5.26                   7.49
4  Saudi Arabia       8418     654.33            5.11                   8.00
5        Mexico        875     634.14            5.13                   7.09
6        Canada      10745     585.25            5.28                   6.86
7         Spain      16700     557.32            5.33                   6.97

# KPI by Income_band

In [18]:
query="""SELECT 
    CASE
        WHEN m.Income < 28240.225 THEN 'Low Income'
        WHEN m.Income <= 86917.575 THEN 'Middle Income'
        ELSE 'High Income'
    END AS Income_band,
    COUNT(*) AS Customers,
    ROUND(AVG(d.Total_Spend),2) AS Avg_Spend,
    ROUND(AVG(m.NumWebVisitsMonth),2) AS Avg_Web_Visits,
    ROUND((SUM(m.AcceptedCmp1)+SUM(m.AcceptedCmp2)+SUM(m.AcceptedCmp3)+SUM(m.AcceptedCmp4)+SUM(m.AcceptedCmp5)+SUM(m.Response))*100.0/(COUNT(*)*6), 2) AS Overall_response_rate
    
    FROM marketing_campaigns_data m
    JOIN derived_table d
    ON m.ID=d.ID
    
    GROUP BY Income_band
    ORDER BY Avg_Spend DESC"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_16204\3744176483.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

     Income_band  Customers  Avg_Spend  Avg_Web_Visits  Overall_response_rate
0    High Income      13997    1116.36            4.16                  12.39
1  Middle Income      27992     629.00            5.16                   7.77
2     Low Income      13997     186.40            6.19                   2.82

# Segmentwise analysis

In [ ]:
query="""SELECT 
    CASE
        WHEN Age BETWEEN 30 AND 44 THEN 'Young Adults'
        WHEN Age BETWEEN 45 AND 59 THEN 'Middle Aged'
        ELSE 'Senior Adults'
    END AS Age_band,
    CASE
        WHEN m.Income < 28240.225 THEN 'Low Income'
        WHEN m.Income <= 86917.575 THEN 'Middle Income'
        ELSE 'High Income'
    END AS Income_band,
    COUNT(*) AS Customers,
    ROUND(AVG(d.Total_Spend),2) AS Avg_Spend,
    ROUND(AVG(m.NumWebVisitsMonth),2) AS Avg_Web_Visits,
    ROUND(AVG(m.MntWines),2) AS Avg_on_wines,
    ROUND(AVG(m.MntFruits),2) AS Avg_on_fruits,
    ROUND(AVG(m.MntMeatProducts),2) AS Avg_on_meat,
    ROUND(AVG(m.MntFishProducts),2) AS Avg_on_fish,
    ROUND(AVG(m.MntSweetProducts),2) AS Avg_on_sweets,
    ROUND(AVG(m.MntGoldProds),2) AS Avg_on_gold,
    ROUND(AVG(m.NumDealsPurchases),2) AS Avg_new_deal,
    ROUND(AVG(m.NumWebPurchases),2) AS Avg_web_pur,
    ROUND(AVG(m.NumCatalogPurchases),2) AS Avg_catalog,
    ROUND(AVG(m.NumStorePurchases),2) AS Avg_store_pur,

    ROUND(AVG(m.AcceptedCmp1) * 100, 2) AS Campaign1_Acceptance_Rate,
    ROUND(AVG(m.AcceptedCmp2) * 100, 2) AS Campaign2_Acceptance_Rate,
    ROUND(AVG(m.AcceptedCmp3) * 100, 2) AS Campaign3_Acceptance_Rate,
    ROUND(AVG(m.AcceptedCmp4) * 100, 2) AS Campaign4_Acceptance_Rate,
    ROUND(AVG(m.AcceptedCmp5) * 100, 2) AS Campaign5_Acceptance_Rate,
    ROUND(AVG(m.Response) * 100, 2) AS Last_Campaign_Response_Rate
    
    FROM marketing_campaigns_data m
    JOIN derived_table d
    ON m.ID=d.ID
    
    GROUP BY Income_band, Age_band
    ORDER BY Avg_Spend DESC"""
#Acceptance rates are calculated in percentage
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_16204\662667755.py:39: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

,Age_band,Income_band,Customers,Avg_Spend,Avg_Web_Visits,Avg_on_wines,Avg_on_fruits,Avg_on_meat,Avg_on_fish,Avg_on_sweets,...,Avg_new_deal,Avg_web_pur,Avg_catalog,Avg_store_pur,Campaign1_Acceptance_Rate,Campaign2_Acceptance_Rate,Campaign3_Acceptance_Rate,Campaign4_Acceptance_Rate,Campaign5_Acceptance_Rate,Last_Campaign_Response_Rate
0,Senior Adults,High Income,5650,1210.22,4.02,509.26,37.77,448.39,100.04,51.38,...,1.95,5.47,3.36,6.19,23.26,2.48,7.31,9.61,9.49,26.81
1,Middle Aged,High Income,5664,1088.64,4.21,446.25,30.35,424.75,88.40,42.81,...,2.03,5.26,3.16,5.98,21.63,2.14,7.42,8.67,8.83,24.52
2,Young Adults,High Income,2683,977.22,4.38,388.66,25.61,392.40,82.09,35.31,...,2.05,5.31,3.10,5.91,20.09,1.79,7.34,8.24,7.23,22.47
3,Senior Adults,Middle Income,9257,730.94,4.98,283.24,18.59,306.02,57.72,25.25,...,2.19,4.59,2.37,5.02,15.96,1.75,7.01,6.23,5.03,16.28
4,Middle Aged,Middle Income,12521,610.26,5.22,223.32,14.02,270.12,48.67,19.45,...,2.22,4.36,2.13,4.77,13.16,1.59,6.68,5.79,4.32,14.02
5,Young Adults,Middle Income,6214,514.90,5.31,188.65,10.10,228.27,40.62,15.43,...,2.21,4.18,1.95,4.58,11.41,1.06,6.50,5.36,3.15,12.83
6,Senior Adults,Low Income,3431,249.87,6.00,78.91,4.25,128.85,17.87,5.89,...,2.29,3.09,1.06,3.37,5.57,0.61,4.52,2.51,1.22,6.21
7,Middle Aged,Low Income,6744,180.27,6.20,53.42,2.73,96.81,12.17,3.72,...,2.26,2.83,0.83,3.13,4.43,0.50,4.23,2.16,0.87,4.92
8,Young Adults,Low Income,3822,140.23,6.36,41.14,1.79,77.19,9.10,2.37,...,2.26,2.65,0.77,3.01,3.24,0.39,3.48,1.54,0.58,3.90