In [1]:
import pandas as pd

clean_df = pd.read_pickle(r"D:\DataScience\GUVI\Local\Marketing_campaign_analysis\cleaned_data.pkl")
clean_df

,ID,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,...,AcceptedCmp2,Response,Complain,Country,Age,Children,Total_Spend,Total_Purchases,Family_Size,Customer_since
0,342199,Graduation,Together,59011.7,1,0,2012-11-17,3,0,2,...,0,0,0,Spain,41,1,69,13,3,4968
1,8075450,Master,Single,1730.0,1,1,2013-04-10,96,0,0,...,0,0,0,Spain,51,2,39,4,3,4824
2,13664263,Graduation,Married,98584.6,0,0,2014-01-11,99,920,0,...,0,0,0,Australia,48,0,1512,12,2,4548
3,16164787,Graduation,Married,74031.5,1,0,2014-06-18,47,265,0,...,0,0,0,Spain,50,1,478,16,3,4390
4,15815139,Graduation,Divorced,52784.2,1,1,2014-05-20,0,30,3,...,0,0,0,Canada,45,2,330,9,3,4419
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55995,2485439,Graduation,Married,32533.4,0,0,2013-04-05,99,8,6,...,0,0,0,Australia,41,0,53,19,2,4829
55996,9202496,Basic,Single,70496.3,0,1,2013-01-31,9,835,0,...,0,0,0,Germany,34,1,924,12,2,4893
55997,14677746,Graduation,Together,21072.0,1,0,2013-06-25,24,0,5,...,0,1,0,Saudi Arabia,76,1,608,5,3,4748
55998,3843719,Graduation,Together,64218.1,0,0,2014-05-12,81,8,4,...,0,0,0,Saudi Arabia,50,0,69,8,2,4427
55999,3195751,Graduation,Married,89322.8,0,1,2013-09-04,93,113,0,...,0,0,0,Saudi Arabia,42,1,262,6,3,4677

In [3]:
high_spend_threshold = clean_df['Total_Spend'].quantile(0.90)
# High Income
clean_df['High_Income'] = clean_df['Income'].apply(lambda x: 'Yes' if x > 86000 else 'No')

# Young Customer (Age < 45)
clean_df['Young_Customer'] = clean_df['Age'].apply(lambda x: 'Yes' if x < 45 else 'No')

# Campaign Responder
campaigns = ['AcceptedCmp1','AcceptedCmp2', 'AcceptedCmp3','AcceptedCmp4', 'AcceptedCmp5','Response']
clean_df['Campaign_Responder'] = clean_df[campaigns].apply(lambda row: 'Yes' if row.sum()>0 else 'No', axis=1)

# High Web Engagement
clean_df['High_Web_Engagement'] = clean_df['NumWebVisitsMonth'].apply(lambda x: 'Yes' if x > 7 else 'No')

# Family Customer
clean_df['Family_Customer'] = clean_df['Children'].apply(lambda x: 'Yes' if x > 0 else 'No')

# High Spender
clean_df['High_Spender'] = clean_df['Total_Spend'].apply(lambda x: 'Yes' if x > high_spend_threshold else 'No')
clean_df

,ID,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,...,Total_Spend,Total_Purchases,Family_Size,Customer_since,High_Income,Young_Customer,Campaign_Responder,High_Web_Engagement,Family_Customer,High_Spender
0,342199,Graduation,Together,59011.7,1,0,2012-11-17,3,0,2,...,69,13,3,4968,No,Yes,No,No,Yes,No
1,8075450,Master,Single,1730.0,1,1,2013-04-10,96,0,0,...,39,4,3,4824,No,No,No,No,Yes,No
2,13664263,Graduation,Married,98584.6,0,0,2014-01-11,99,920,0,...,1512,12,2,4548,Yes,No,No,No,No,No
3,16164787,Graduation,Married,74031.5,1,0,2014-06-18,47,265,0,...,478,16,3,4390,No,No,No,No,Yes,No
4,15815139,Graduation,Divorced,52784.2,1,1,2014-05-20,0,30,3,...,330,9,3,4419,No,No,No,No,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55995,2485439,Graduation,Married,32533.4,0,0,2013-04-05,99,8,6,...,53,19,2,4829,No,Yes,No,Yes,No,No
55996,9202496,Basic,Single,70496.3,0,1,2013-01-31,9,835,0,...,924,12,2,4893,No,Yes,No,No,Yes,No
55997,14677746,Graduation,Together,21072.0,1,0,2013-06-25,24,0,5,...,608,5,3,4748,No,No,Yes,No,Yes,No
55998,3843719,Graduation,Together,64218.1,0,0,2014-05-12,81,8,4,...,69,8,2,4427,No,No,No,Yes,No,No
55999,3195751,Graduation,Married,89322.8,0,1,2013-09-04,93,113,0,...,262,6,3,4677,Yes,Yes,No,No,Yes,No

In [4]:
clean_df.to_pickle('incl_segmentation.pkl')