In [1]:
import pandas as pd
import numpy as np
import mysql.connector 

connection = mysql.connector.connect(
    host = "Localhost",
    user = "root",
    password = "12345",
    database="market_analysis"
)
cursor =  connection.cursor()
cursor

# Income Segmentation

In [ ]:
query = """SELECT 
    CASE
        WHEN Income < 28240.225 THEN 'Low Income'
        WHEN Income <= 86917.575 THEN 'Middle Income'
        ELSE 'High Income'
    END AS Income_band,
    Count(*) AS Customer_Count
    FROM marketing_campaigns_data 
    Group BY Income_band"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_8608\1610432973.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

  Income_segmentation  Customer_Count
0          Low Income           13997
1       Middle Income           27992
2         High Income           14011

# Age Segmentation

In [20]:
query="""SELECT
    CASE
        WHEN Age<45 THEN 'Young'
        When Age BETWEEN 45 and 63 THEN 'Middle aged'
        ELSE 'Senior'
        END AS Age_band,
        COUNT(*) AS Customer_COUNT
        FROM derived_table
        GROUP BY Age_band"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_8608\3112352697.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

      Age_band  Customer_COUNT
0       Senior           13100
1  Middle aged           30167
2        Young           12719

# Campaign Segmentation

In [ ]:
# Accepted atleast one campaign
query="""SELECT
    CASE 
        WHEN AcceptedCmp1 = 1
          OR AcceptedCmp2 = 1
          OR AcceptedCmp3 = 1
          OR AcceptedCmp4 = 1
          OR AcceptedCmp5 = 1
          OR Response = 1
        THEN 'Yes'
        ELSE 'No'
        END AS Accepted_campaign,
        COUNT(*) AS Customer_count
        From marketing_campaigns_data
        GROUP BY Accepted_campaign"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_8608\4142651864.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

  Accepted_campaign  Customer_count
0                No           35611
1               Yes           20389

In [14]:
query="""SELECT
    'Campaign 1' AS Campaign,
    COUNT(CASE WHEN AcceptedCmp1 = 1 THEN 1 END) AS Accepted
FROM marketing_campaigns_data

UNION ALL

SELECT
    'Campaign 2',
    COUNT(CASE WHEN AcceptedCmp2 = 1 THEN 1 END)
FROM marketing_campaigns_data

UNION ALL

SELECT
    'Campaign 3',
    COUNT(CASE WHEN AcceptedCmp3 = 1 THEN 1 END)
FROM marketing_campaigns_data

UNION ALL

SELECT
    'Campaign 4',
    COUNT(CASE WHEN AcceptedCmp4 = 1 THEN 1 END)
FROM marketing_campaigns_data

UNION ALL

SELECT
    'Campaign 5',
    COUNT(CASE WHEN AcceptedCmp5 = 1 THEN 1 END)
FROM marketing_campaigns_data

UNION ALL

SELECT
    'Latest Campaign',
    COUNT(CASE WHEN Response = 1 THEN 1 END)
FROM marketing_campaigns_data"""

df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_8608\1047503631.py:41: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

          Campaign  Accepted
0       Campaign 1      7529
1       Campaign 2       807
2       Campaign 3      3494
3       Campaign 4      3182
4       Campaign 5      2557
5  Latest Campaign      8265

# Web Engagement Segmentation

In [21]:
query="""SELECT
    CASE
        WHEN NumWebVisitsMonth > 7 THEN 'High engagement'
        WHEN NumWebVisitsMonth Between 3 AND 7 THEN 'Average engagement'
        ELSE 'Low engagement'
        END AS Web_engagement_band,
        COUNT(*) AS Customer_count
        From marketing_campaigns_data
        GROUP BY Web_engagement_band"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_8608\254195908.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

  Web_engagement_band  Customer_count
0      Low engagement           10127
1  Average engagement           33179
2     High engagement           12694

# Family segmentation

In [22]:
query="""SELECT
    CASE
        WHEN kidhome>=1 THEN 'Parent of a child'
        WHEN teenhome>=1 THEN 'Parent of a teen'
        ELSE 'Adult'
        END AS Family_band,
        COUNT(*) AS Customer_count
        FROM marketing_campaigns_data
        GROUP BY Family_band"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_8608\390347178.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

         Family_band  Customer_count
0  Parent of a child           29580
1   Parent of a teen            8642
2              Adult           17778

# Spender segmentation

In [25]:
query="""SELECT
    CASE
        WHEN Total_Spend < 441 THEN 'Low spender'
        WHEN Total_Spend < 1600 THEN 'Medium spender'
        ELSE 'High spender'
    END AS Spend_segment,
    COUNT(*) AS Customer_Count
    FROM derived_table
    GROUP BY Spend_segment"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_8608\48561541.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

    Spend_segment  Customer_Count
0  Medium spender           22821
1     Low spender           27952
2    High spender            5213

# Combined segmentation

In [5]:
query="""SELECT 
    CASE
        WHEN m.Income < 28240.225 THEN 'Low Income'
        WHEN m.Income <= 86917.575 THEN 'Middle Income'
        ELSE 'High Income'
    END AS Income_band,
    
    CASE
        WHEN d.Age<45 THEN 'Young'
        When d.Age BETWEEN 45 and 63 THEN 'Middle aged'
        ELSE 'Senior'
    END AS Age_band,
    
    CASE
        WHEN m.NumWebVisitsMonth > 7 THEN 'High engagement'
        WHEN m.NumWebVisitsMonth Between 3 AND 7 THEN 'Average engagement'
        ELSE 'Low engagement'
    END AS Web_engagement_band,
    
    CASE
        WHEN m.Kidhome >= 1 AND m.Teenhome >= 1 THEN 'Parent of child & teen'
        WHEN m.kidhome>=1 THEN 'Parent of a child'
        WHEN m.teenhome>=1 THEN 'Parent of a teen'
        ELSE 'Adult'
    END AS Family_band,
    
    CASE
        WHEN d.Total_Spend < 441 THEN 'Low spender'
        WHEN d.Total_Spend < 1600 THEN 'Medium spender'
        ELSE 'High spender'
    END AS Spend_segment,
    
    COUNT(*) AS Customer_Count,

    SUM(CASE WHEN m.AcceptedCmp1 = 1 THEN 1 ELSE 0 END) AS Campaign1_Accepted,
    SUM(CASE WHEN m.AcceptedCmp2 = 1 THEN 1 ELSE 0 END) AS Campaign2_Accepted,
    SUM(CASE WHEN m.AcceptedCmp3 = 1 THEN 1 ELSE 0 END) AS Campaign3_Accepted,
    SUM(CASE WHEN m.AcceptedCmp4 = 1 THEN 1 ELSE 0 END) AS Campaign4_Accepted,
    SUM(CASE WHEN m.AcceptedCmp5 = 1 THEN 1 ELSE 0 END) AS Campaign5_Accepted,
    SUM(CASE WHEN m.Response = 1 THEN 1 ELSE 0 END) AS Latest_Campaign_Accepted

    FROM marketing_campaigns_data m
    JOIN derived_table d
    ON m.ID = d.ID
    Group BY Income_band, Age_band, Web_engagement_band, Family_band, Spend_segment

    ORDER BY Customer_count DESC"""
df=pd.read_sql(query, connection)
df

C:\Users\hamsa\AppData\Local\Temp\ipykernel_3320\530026602.py:48: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(query, connection)

,Income_band,Age_band,Web_engagement_band,Family_band,Spend_segment,Customer_Count,Campaign1_Accepted,Campaign2_Accepted,Campaign3_Accepted,Campaign4_Accepted,Campaign5_Accepted,Latest_Campaign_Accepted
0,Low Income,Middle aged,Average engagement,Parent of a child,Low spender,2427,85.0,11.0,97.0,44.0,14.0,88.0
1,Middle Income,Middle aged,Average engagement,Parent of a child,Low spender,1948,170.0,18.0,122.0,74.0,35.0,170.0
2,Middle Income,Middle aged,Average engagement,Adult,Medium spender,1542,281.0,26.0,118.0,128.0,113.0,313.0
3,Low Income,Middle aged,Average engagement,Parent of child & teen,Low spender,1410,42.0,7.0,54.0,29.0,3.0,50.0
4,Low Income,Middle aged,High engagement,Parent of a child,Low spender,1279,36.0,3.0,44.0,17.0,6.0,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...
310,Low Income,Senior,Low engagement,Parent of a child,High spender,1,0.0,0.0,0.0,0.0,0.0,0.0
311,Low Income,Senior,Low engagement,Parent of child & teen,High spender,1,0.0,0.0,0.0,0.0,0.0,0.0
312,Low Income,Young,Average engagement,Parent of a teen,High spender,1,0.0,0.0,0.0,0.0,0.0,0.0
313,Low Income,Young,High engagement,Parent of a child,High spender,1,0.0,0.0,0.0,0.0,0.0,0.0
314,Low Income,Young,Low engagement,Parent of a teen,Medium spender,1,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
df.columns

Index(['Income_band', 'Age_band', 'Web_engagement_band', 'Family_band',
       'Spend_segment', 'Customer_Count', 'Campaign1_Accepted',
       'Campaign2_Accepted', 'Campaign3_Accepted', 'Campaign4_Accepted',
       'Campaign5_Accepted', 'Latest_Campaign_Accepted'],
      dtype='str')

In [30]:
#convert int columns to int

int_cols = ['Customer_Count', 'Campaign1_Accepted', 'Campaign2_Accepted', 'Campaign3_Accepted', 'Campaign4_Accepted', 
    'Campaign5_Accepted', 'Latest_Campaign_Accepted']

df[int_cols] = df[int_cols].astype(int)

In [9]:
query="drop table sql_segmentation_table"
cursor.execute(query)
connection.commit()

In [10]:
query = """create table if not exists sql_segmentation_table(Income_band varchar(60), Age_band varchar(60), 
       Web_engagement_band varchar(60), Family_band varchar(60), Spend_segment varchar(60), Customer_Count int, Campaign1_Accepted int,
       Campaign2_Accepted int, Campaign3_Accepted int, Campaign4_Accepted int, Campaign5_Accepted int, Latest_Campaign_Accepted int)"""
cursor.execute(query)
connection.commit()

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 315 entries, 0 to 314
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Income_band               315 non-null    str
 1   Age_band                  315 non-null    str
 2   Web_engagement_band       315 non-null    str
 3   Family_band               315 non-null    str
 4   Spend_segment             315 non-null    str
 5   Customer_Count            315 non-null    int64
 6   Campaign1_Accepted        315 non-null    float64
 7   Campaign2_Accepted        315 non-null    float64
 8   Campaign3_Accepted        315 non-null    float64
 9   Campaign4_Accepted        315 non-null    float64
 10  Campaign5_Accepted        315 non-null    float64
 11  Latest_Campaign_Accepted  315 non-null    float64
dtypes: float64(6), int64(1), str(5)
memory usage: 48.7 KB

In [11]:
columns = ",".join(df.columns)
placeholders = ",".join(["%s"]*len(df.columns))
query = f"insert into sql_segmentation_table({columns}) values({placeholders})"
tuple_data = []

for idx in df.index:
    row = list(df.loc[idx].values)
    for j in range(len(row)):
        if isinstance(row[j], (np.integer, np.int64)):
            row[j] = int(row[j])

    tuple_data.append(row)
   
cursor.executemany(query, tuple_data)
connection.commit()